### ISSUE TITLE
problem with tx_mmdamfilelist

### ISSUE THREAD

**Issue by nurbs999** [comvos/comvosfilelist#2]
I try to use comvosfilelist as an replacement for the old mmdam_filelist. I have DAM db with about 20k images and after installing the comvosfilelist extension and removing mmdam_filelist, I get this error when I call the index site of my images:
Fatal error: Class 'tx_mmdamfilelist_pi1' not found in /var/www/localhost/htdocs/typo3_src-4.5.25/t3lib/class.t3lib_div.php on line 5376
To me, it seems like the comvosfilelist extension missed to register the fake_mmdam_filelist.

**Comment by nsaleh** [comment]
Hi, 

did you activate the replacement in the extension configuration? yes? then propably you didn't register comvosfilelist to render mm_damfilelist in TS-Setup. please check 
https://github.com/comvos/comvosfilelist/blob/master/static/default/setup.txt

> #to replace existing mm_dam_filelist plugins with comvosfilelistplugin add this line 
> #tt_content.list.20.mm_dam_filelist_pi1 =< plugin.tx_comvosfilelist_pi1

Did you remove all mm_damfilelist TS and uninstall the extension already? If you didn't, that might have bad sideeffects, too.

If this solved the problem please close the issue otherwise we can look further.

cheers Nabil

**Comment by nurbs999** [comment]
my fault, thanks a lot for your quick answer!
